version: '3.8'

services:

  lb1:
    build: lb1/
    container_name: lb1
    networks:
      - cluster
    privileged: true
    ports:
      - "8081:80"

  lb2:
    build: lb2/
    container_name: lb2
    networks:
      - cluster
    privileged: true
    depends_on:
      - lb1
    ports:
      - "8082:80"

  backend1:
    build: backend1/
    container_name: backend1
    networks:
      - cluster
    depends_on:
      - lb1
      - lb2

  backend2:
    build: backend2/
    container_name: backend2
    networks:
      - cluster
    depends_on:
      - lb1
      - lb2  

  host:
    build: host/
    container_name: host
    networks:
      - cluster
    depends_on:
      - lb1
      - lb2
      - backend1
      - backend2
    privileged: true
    volumes:
      - ./host/ansible:/ansible

networks:
  cluster:
    driver: bridge
